[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
drip_raffle = "8dctDFAvn58rNoBbykB6PSakMYh3HdANBbHsbvoLtuep"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/pratik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/drip_raffle.ts"
